### ISSUE TITLE
[Request] An option to delete all trainers from the PS4

### ISSUE THREAD

**Issue by ghost** [bucanero/PS4CheatsManager#105]
When a PS4 updates the trainers using GoldHEN Cheats Manager, it does not delete already existing ones on the PS4. Having an option to delete them would be wonderful. I'm more than aware that I can do that now by using FTP, but an option for the newbies would be preferable.

P.S: I'm currently oblivious as to whether or not such an option currently exists, but I've personally never found one.

**Comment by bucanero** [comment]
Right now you have an option under `Settings` to "Overwrite files", if you enable it, when an update pack is downloaded any duplicate file will be overwritten with the new data.
(if disabled, no files will be overwritten, so your old files remain)

I guess you want an option to clean everything, and remove all the files/cheats/patches.

**Comment by bucanero** [comment]
fixed in 098b9860efbcdf5fd330f339c69d251d255e5fde
