### ISSUE TITLE
Copying cheats from USB instead of downloading them?

### ISSUE THREAD

**Issue by doctahoo** [bucanero/PS4CheatsManager#11]
Hi, congrats for this excellent software!

One suggestion for a future update: How about the possibility to copy cheats from a USB folder to the HDD for those who are not connected to the Internet? It would be something like an "**offline cheat update**" feature (very much like the USB to HDD save copy function from your excellent Apollo Save Tool). And maybe also a "**cheat backup**" feature for backing up all or a few selected cheats from HDD to USB.

Copying cheats from USB to HDD with Lapy's PS4 Xplorer application is quite unreliable since you cannot copy a whole folder containing 300 or 400 cheat files at once (not all cheats inside the folder are copied), and copying them all over manually is really tedious!

**Comment by bucanero** [comment]
Yes, it could be a good feature for users that have their ps4 offline.

For the update I see two possible options:
- [x] update cheats from USB with a .ZIP file (read the zip and extract to HDD)
- [ ] update cheats from USB by copying plain folders (`json/`, `shn/`, etc)

The backup/export could be also a good feature:
- [ ] backup current cheats to USB (plain text files)
- [x] backup current cheats to ZIP (could be saved to USB or HDD)

**Comment by doctahoo** [comment]
Yes, that sounds really good. All these options for different people's needs would make this tool definitely more flexible to use and handy.

**Comment by bucanero** [comment]
I've added the offline cheat pack install from USB (or HDD) to the latest 0.7.0 version.
To use it:
- download the latest [cheat pack from GH Cheat Repository](https://github.com/GoldHEN/GoldHEN_Cheat_Repository/archive/refs/heads/main.zip) (`GoldHEN_Cheat_Repository-main.zip`)
- copy `GoldHEN_Cheat_Repository-main.zip` to a USB drive (root folder) or HDD (/data/ folder)
  - `/mnt/usb0/GoldHEN_Cheat_Repository-main.zip`
  - `/data/GoldHEN_Cheat_Repository-main.zip`
- open Cheat Manager, and click **Update**
- the Manager will detect the offline pack and extract it to the required folder

**Comment by doctahoo** [comment]
Fantástico, bucanero! Eso hay que probarlo!
