### ISSUE TITLE
cheats manager won't load COD MW3 cheat!

### ISSUE THREAD

**Issue by krimnassim** [bucanero/PS4CheatsManager#111]
i can't load cod mw3 cheat i'm using the latest cheat manager v1.2.0 the issue only happens with cod all other games load cheats just fine the cod mw3 cheat is loaded on cheat manager menu like shown in the pictures but won't work hope fix soon thanx.
![IMG_20240108_144620](https://github.com/bucanero/PS4CheatsManager/assets/62130284/447030d0-a5e2-43b1-958d-af8d1c992f10)
![IMG_20240108_145122](https://github.com/bucanero/PS4CheatsManager/assets/62130284/b285ff00-c4fb-4382-b43e-981025a710e8)
![IMG_20240108_145159](https://github.com/bucanero/PS4CheatsManager/assets/62130284/8b23915c-b809-4b04-9781-0b39218a024d)

**Comment by bucanero** [comment]
the cheat manager is only a tool to list files, the Goldhen payload is the one detecting and applying cheats. 

Report or check on the Goldhen repository.
