### ISSUE TITLE
Stubbon cheats problem

### ISSUE THREAD

**Issue by BA0123** [bucanero/PS4CheatsManager#113]
Hi,

I have applied the "Boost XP" cheat (without any indication in the program that it was applied) to FFVII, but I can't possibly turn it off.

I tried the following:
1- Re-install Cheats manager
2- Clear the game's save data
3- Selected the same cheat again to deactivate it

However, none of the above worked. Is there a way to deal with this?

Thanks

**Comment by bucanero** [comment]
the cheat manager is only a tool to list files, the Goldhen payload is the one detecting and applying cheats.

Report or check on the Goldhen repository.
