### ISSUE TITLE
Trying to Build Pre-disabled Animation PKG

### ISSUE THREAD

**Issue by IRONB0SS** [bucanero/PS4CheatsManager#118]
![image](https://github.com/user-attachments/assets/e08c38b5-ba89-4db9-aa5f-896aac73eb0d)

Hey Damián, Is It possible to send modified file that menu animation is disabled by default

Thanks in advance

**Comment by bucanero** [comment]
you can disable animations under "Settings", once you save changes it won't do any animations.

**Comment by IRONB0SS** [comment]
> you can disable animations under "Settings", once you save changes it won't do any animations.

Hey I know that but I'm looking for pre-disabled file :))
