### ISSUE TITLE
Online Cheat DB crashing app once clicked on

### ISSUE THREAD

**Issue by illusionalDEX** [bucanero/PS4CheatsManager#119]

**Comment by bucanero** [comment]
it's probably an issue from the online database data, but I'll check it out.

In any case, there's nothing critical on the online DB, if you click on "update" you'll get all the latest cheats on your ps4.

**Comment by bucanero** [comment]
the problem was due to broken data files.

The issue has been fixed on the database files: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/pull/407

(the app could be improved in the future to skip any broken files)
