### ISSUE TITLE
Select other cheat files

### ISSUE THREAD

**Issue by neo305** [bucanero/PS4CheatsManager#12]
Some games have more than one cheat file. Would be nice to select the other file using L & R Buttons

**Comment by bucanero** [comment]
Keep in mind: the cheat list is for information only, you can't select or activate any cheats using the cheat Manager.

**Comment by neo305** [comment]
What are you talking about cuz I'm talking about the json files ![image](https://user-images.githubusercontent.com/25275928/159164458-dd9c2758-27ab-4d47-9ddc-28f69722cd32.jpeg) there is usually more than 1 but we are only able to select/see 1 and not the other.

**Comment by bucanero** [comment]
That's GoldHEN embedded cheat Engine, completely different from the [Cheat Manager](https://goldhen.github.io/GoldHEN_Cheat_Manager/) homebrew application.

Open your request here: https://github.com/GoldHEN/GoldHEN/issues

**Comment by bucanero** [comment]
tagging @SiSTR0 just in case.
