### ISSUE TITLE
Juegos que aunque estan actualizados ejemplo mad max 1.14 en version sigue apareciendo la 1.00 y si miro el histórico de actualización aparece 1 14 

### ISSUE THREAD

**Issue by bombardeo38** [bucanero/PS4CheatsManager#15]
Hay problemas con los juegos que ya incluyen la actualización y no cambia la versión en el apartado informacion otra cosa en days gone 1.51 no se exactamente activando el que las grabadoras nero no se cogen me a pasado en el puesto de nero de old pioner gracias de antemano

**Comment by bucanero** [comment]
See notes here https://github.com/GoldHEN/GoldHEN_Cheat_Manager/issues/4#issuecomment-1087980154
