### ISSUE TITLE
This is an issue from the fpkg that has a wrong version defined. I've checked with @SiSTR0 and we are not going to support these fake packages with wrong versions.

### ISSUE THREAD

**Issue by bombardeo38** [bucanero/PS4CheatsManager#17]
This is an issue from the fpkg that has a wrong version defined. I've checked with @SiSTR0 and we are not going to support these fake packages with wrong versions.

You still have a workaround: just rename the file to match the `01.00` version and GoldHEN will load the cheats.
Another option: create a dummy update package that just updates the version to the correct one.

_Originally posted by @bucanero in https://github.com/GoldHEN/GoldHEN_Cheat_Manager/issues/4#issuecomment-1087980154_
Podías explicar o decir con que aplicación hacer la actualización ficticia te lo agradeceríamos mucho

**Comment by bucanero** [comment]
Maybe you can check these tools: https://www.psxhax.com/threads/ps4-aio-batch-file-script-for-games-updates-with-fpkg-tools-by-jation.12537/

**Comment by bombardeo38** [comment]
Gracias pero el enlace esta caido
