### ISSUE TITLE
Custom Cheat Files

### ISSUE THREAD

**Issue by SaWkYmOd** [bucanero/PS4CheatsManager#20]
Maybe a new feature. .
I created a custom JSON file and replaced the original from the cheats folder on the PS4 ..But everytime I update the cheat list my custom file is overwritten...is there a way to stop certain files being overwritten when updating....

Cheers

**Comment by bucanero** [comment]
well, if you have added any useful cheat codes, you could just submit the changes here:
https://github.com/GoldHEN/GoldHEN_Cheat_Repository/issues/new/choose

then next time you update, you'll download the improved cheat file.

Right now files are overwritten so if you have custom stuff, you need to keep a copy somewhere else or just avoid the updater.

**Comment by bucanero** [comment]
See #42
