### ISSUE TITLE
Update cheats not working

### ISSUE THREAD

**Issue by jivemaster2005** [bucanero/PS4CheatsManager#22]
On Goldhen v2.2.2 and PS¤ Pro with 9.00 firmware
Running latest version of Goldhen cheats manager 0.5.1

My problem is that nothing happens when I try to update the locally installed cheats from the online database.
I get no error message and the screen just flickers when I press update.

**Comment by bucanero** [comment]
The latest version is 0.6.0, you should try updating to the latest version first. Download it from the [Releases](https://github.com/GoldHEN/GoldHEN_Cheat_Manager/releases/tag/v0.6.0)  section on GitHub.

If the issue is still present when using v0.6.0, go to Settings, enable "debug logs" and try to update cheats. Then exit the app and share the log file: `/data/GoldHEN/goldcheats.log`.

**Comment by thebackofmyhea** [comment]
Thanks for reaching out @bucanero 

I'm the same user that commented on the reddit post here: https://www.reddit.com/r/ps4homebrew/comments/te9vjo/comment/i4k7zz6/?utm_source=share&utm_medium=web2x&context=3

PS4 Pro running on 5.05, GoldHEN v2.2.2, Cheats Manager v0.6.0
Debug log: (attached)

Thank you
[goldcheats.log](https://github.com/GoldHEN/GoldHEN_Cheat_Manager/files/8585629/goldcheats.log)

**Comment by jivemaster2005** [comment]
> The latest version is 0.6.0, you should try updating to the latest version first. Download it from the [Releases](https://github.com/GoldHEN/GoldHEN_Cheat_Manager/releases/tag/v0.6.0) section on GitHub.
> 
> If the issue is still present when using v0.6.0, go to Settings, enable "debug logs" and try to update cheats. Then exit the app and share the log file: `/data/GoldHEN/goldcheats.log`.

My mistake. 
Found out I was using an older version and thougjt it updated online since after each start I get a promt that a newer version is found and It goes thru the update procedure

**Comment by thebackofmyhea** [comment]
@jivemaster2005 Is it working for u? I'm on the latest version and both the online and the update options won't work.

**Comment by jivemaster2005** [comment]
> @jivemaster2005 Is it working for u? I'm on the latest version and both the online and the update options won't work.

Yes. It works now on the latest version

**Comment by bucanero** [comment]
> PS4 Pro running on 5.05, GoldHEN v2.2.2, Cheats Manager v0.6.0 Debug log: (attached)
> 
> Thank you [goldcheats.log](https://github.com/GoldHEN/GoldHEN_Cheat_Manager/files/8585629/goldcheats.log)

based on the logs, your connection is failing in the internal PS4 HTTP library with error `0x809517D5` (SSL_ERROR_OUT_OF_MEMORY)

it's really weird, as the connection settings are working fine for other users. Are you loading other stuff in memory, like trainers, ps4debug, toolbox, etc? I'd suggest trying with a clean boot, just the jailbreak and running the cheat manager app. Enable logs and try a few times to update or browse the "online DB". If it keeps failing upload the logs to see if the same error shows up.

**Comment by thebackofmyhea** [comment]
> > PS4 Pro running on 5.05, GoldHEN v2.2.2, Cheats Manager v0.6.0 Debug log: (attached)
> > Thank you [goldcheats.log](https://github.com/GoldHEN/GoldHEN_Cheat_Manager/files/8585629/goldcheats.log)
> 
> based on the logs, your connection is failing in the internal PS4 HTTP library with error `0x809517D5` (SSL_ERROR_OUT_OF_MEMORY)
> 
> it's really weird, as the connection settings are working fine for other users. Are you loading other stuff in memory, like trainers, ps4debug, toolbox, etc? I'd suggest trying with a clean boot, just the jailbreak and running the cheat manager app. Enable logs and try a few times to update or browse the "online DB". If it keeps failing upload the logs to see if the same error shows up.

Nope, I'm just running the jailbreak and injecting GoldHEN through Leeful's payload host I have cached on my web browser.

You just mentioned the error code being an OOM so I thought maybe it's from the cached payload host being too big with the cached payloads and stuff, so I tried the following:

Deleted web site cache and cookies from the web browser settings.
Cached al-azifs dns to the user guide, which should be fairly standard and not as big as the previous cached host I had.
Rebooted the system, deleted GoldHEN save data and re-installed the 0.6.0
Ran the Cheat Manager app. 

I believe it's throwing the same error code, here's the log file.
[goldcheats.log](https://github.com/GoldHEN/GoldHEN_Cheat_Manager/files/8599351/goldcheats.log)

**Comment by thebackofmyhea** [comment]
Here’s another report I found online regarding this issue, last comment. http://www.logic-sunrise.com/forums/topic/95672-ps4-goldhen-cheats-manager-v060-disponible/
