### ISSUE TITLE
Can we use a shortter when importing usb cheats

### ISSUE THREAD

**Issue by Serendo** [bucanero/PS4CheatsManager#31]
the current cheats pack name is too long. Maybe we can use just cheats.zip instead of GoldHEN_Cheat_Repository-main.zip?

**Comment by bucanero** [comment]
that's the generated filename when you download the latest .Zip from Github:
https://github.com/GoldHEN/GoldHEN_Cheat_Repository/archive/refs/heads/main.zip

it's easier to keep it like this so there's no need to rename files. Just download from github, and copy to a USB drive.

**Comment by illusionyy** [comment]
Fixed in #98
