### ISSUE TITLE
Error: Use of undeclared Identifer "(Orbis_sysmodule_Internal_pad) < 0)

### ISSUE THREAD

**Issue by sjdo** [bucanero/PS4CheatsManager#34]
Error: Use of undeclared Identifer "(Orbis_sysmodule_Internal_pad) < 0)

**Comment by bucanero** [comment]
Update the Open Orbis header files.

**Comment by sjdo** [comment]
it is up2date

**Comment by bucanero** [comment]
https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/blob/master/include/orbis/_types/sysmodule.h
