### ISSUE TITLE
Problema con varios juegos

### ISSUE THREAD

**Issue by bombardeo38** [bucanero/PS4CheatsManager#39]
No se si es el hen nuevo apesar de última actualización del manager pero cuando los juegos desaparecen de la lista que no son marcados con la estrella aunque pulsando el boton puedas activar los trucos no se activan e probado en el valhalla y el causa justa 3 pero con el entrenador desde el móvil si que funcionan

**Comment by bucanero** [comment]
This has nothing to do with the manager. I already told you that cheats are handled by the payload.
