### ISSUE TITLE
[feature suggestion] the ability to pick a specific cheat/file.

### ISSUE THREAD

**Issue by ItsOuba** [bucanero/PS4CheatsManager#4]
it would be great if you can add a cheat/file picker, i'll give an example for the reason i'm asking for that. i have Ghost of Tsushima with the update 2.13 included in the fpkg base file, but when you press the option button to check game version it will show version 1.00, but when you check update history you'll see that it is 2.13 . the cheat that is being loaded is for 1.00 because it is the "game version" but it won't work because of what i explained earlier . so it would be helpful if the manager can show all the cheats versions available for the game and we pick one

**Comment by bucanero** [comment]
This is an issue from the fpkg that has a wrong version defined. I've checked with @SiSTR0 and we are not going to support these fake packages with wrong versions.

You still have a workaround: just rename the file to match the `01.00` version and GoldHEN will load the cheats.
Another option: create a dummy update package that just updates the version to the correct one.
