### ISSUE TITLE
Add game patch support

### ISSUE THREAD

**Issue by bucanero** [bucanero/PS4CheatsManager#41]
Add game patches from @illusion0001 

- [x] add a new `Patches` main menu
- [x] list and parse game patch files
- [x] patch files path: `/data/GoldHEN/patches/json`
- [x] allow patches updating from the web (download + unzip)
- [x] allow enabling/disabling patches

**Comment by illusionyy** [comment]
3-5 are completed on my branch https://github.com/illusion0001/GoldHEN_Cheat_Manager/commit/e799eade9a92ff398342d34233512d891afadc6d. though I have yet to figure out how to use `list_append` method at this time.

**Comment by bucanero** [comment]
> 3-5 are completed on my branch [illusion0001@e799ead](https://github.com/illusion0001/GoldHEN_Cheat_Manager/commit/e799eade9a92ff398342d34233512d891afadc6d). though I have yet to figure out how to use `list_append` method at this time.

Great, I'll work on 1-2 and then we can merge your changes into the `game-patch-support` branch to test if everything works as expected 👍
