### ISSUE TITLE
The new filter for installed games/cheats is not detecting some games

### ISSUE THREAD

**Issue by Abdalkarem1** [bucanero/PS4CheatsManager#51]
The new filter for installed games/cheats is not detecting some games e.g. god of war ragnarok CUSA34390 – v2.00  on the HDD Cheats menu.

But, it shows the game on the Online Cheats list.

**Comment by mayurss786** [comment]
same issue with me on CUSA34380

**Comment by bucanero** [comment]
Just to be clear, the Cheats manager app has nothing to do with applying cheats, so detection or filtering is only for cosmetic reasons and has no effect at all. (Applying cheats is done by the GoldHEN payload itself)

For example, you don't need to use the Cheat Manager for the cheats to be loaded or detected. Use the manager only if you want to update the cheat database with the latest cheats.

**Comment by bucanero** [comment]
See GoldHEN/GoldHEN_Cheat_Manager#27
