### ISSUE TITLE
Petition 

### ISSUE THREAD

**Issue by Bolter590** [bucanero/PS4CheatsManager#56]
Could you please tell me how to get the cheats for this version CUSA07708 Monster Hunter Wold Iceborne 15.11 please I need it. 

> And if they manage to pass me the code, in which folder of the ps4 do I have to put the trick?

**Comment by bucanero** [comment]
This is not the place for cheat requests. Read https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42 for more details.
