### ISSUE TITLE
Game Patches don't want to extract

### ISSUE THREAD

**Issue by OliverTauloski** [bucanero/PS4CheatsManager#63]
After I try to update the cheats and the patcher in the Cheat Manager the patches don't want to extract. Is it just me or is there some repository problem.
![PXL_20221127_173743567 MP](https://user-images.githubusercontent.com/71967660/204148480-ea349c66-fc28-4fa1-8d65-6a18f4aa182f.jpg)

**Comment by bucanero** [comment]
You'll need to provide more details, like firmware version, payload, if you're running any other application, tool, mod, etc.

Under "Settings", do you have the "overwrite" option enabled or disabled?

also, do you have a `/data/GoldHEN/patches/` folder? if you have a folder, do you have any files inside that folder?

if you go to the "Patches" menu, do you get a list of patches?

**Comment by OliverTauloski** [comment]
My firmware is 9.00, the host is kamelons host, i dont have any mods or tools.
"overwrite file on update" is enabeled.
In /data/GoldHEN/patches/ there are two folder "json" and "settings" which don't contain anything inside them.
When I go to "Patches" menu it says no cheat codes found.

**Comment by illusionyy** [comment]
Try this build https://github.com/GoldHEN/GoldHEN_Cheat_Manager/suites/9525965008/artifacts/452560745

**Comment by bucanero** [comment]
> My firmware is 9.00, the host is kamelons host, i dont have any mods or tools. "overwrite file on update" is enabeled. In /data/GoldHEN/patches/ there are two folder "json" and "settings" which don't contain anything inside them. When I go to "Patches" menu it says no cheat codes found.

I don't have 9.00fw and I can't reproduce it, but I'd suggest to:
- use an older goldhen payload, such as 2.2.2
- remove the `data/goldhen/patches` folder and everything inside, then run the app again, see if you get the patches installed or not
- if you can't remove the `data/GoldHEN/patches/` folder, try renaming it like `data/goldhen/junk`, then try to create a `patches` folder manually and run the "update" from the app

I'll let @illusion0001 follow this issue as he has been gathering information and feedback about it.

**Comment by OliverTauloski** [comment]
> My firmware is 9.00, the host is kamelons host, i dont have any mods or tools. "overwrite file on update" is enabeled. In /data/GoldHEN/patches/ there are two folder "json" and "settings" which don't contain anything inside them. When I go to "Patches" menu it says no cheat codes found.

I tried the version you sent me but still same thing.

**Comment by OliverTauloski** [comment]
@illusion0001 I tried the built you sent me and still the same thing.

**Comment by OliverTauloski** [comment]
> > My firmware is 9.00, the host is kamelons host, i dont have any mods or tools. "overwrite file on update" is enabeled. In /data/GoldHEN/patches/ there are two folder "json" and "settings" which don't contain anything inside them. When I go to "Patches" menu it says no cheat codes found.
> 
> I don't have 9.00fw and I can't reproduce it, but I'd suggest to:
> 
> * use an older goldhen payload, such as 2.2.2
> * remove the `data/goldhen/patches` folder and everything inside, then run the app again, see if you get the patches installed or not
> * if you can't remove the `data/GoldHEN/patches/` folder, try renaming it like `data/goldhen/junk`, then try to create a `patches` folder manually and run the "update" from the app
> 
> I'll let @illusion0001 follow this issue as he has been gathering information and feedback about it.

@bucanero Thank you soo much. It works now. It downloaded and extracted both the cheats and the patches.
Ps. Keep doing what all of you are doing now, keep up the good work, you are all goats. 🐐👏👏

**Comment by illusionyy** [comment]
Reopening and it's not entirely fixed, if anyone still has the issue they can try #65
https://github.com/GoldHEN/GoldHEN_Cheat_Manager/suites/9572870668/artifacts/455870244

**Comment by OliverTauloski** [comment]
@illusion0001 I also noticed that the 60 FPS patch on Elden Ring doesn't work. I tried the 60FPS patch plus the resolution patch to 720p but it is still 1080p and 27-30 FPS. Ps. I have the base PS4

**Comment by illusionyy** [comment]
Provide more info here: https://github.com/GoldHEN/GoldHEN_Patch_Repository/issues/3

**Comment by bucanero** [comment]
> Reopening and it's not entirely fixed, if anyone still has the issue they can try #65 https://github.com/GoldHEN/GoldHEN_Cheat_Manager/suites/9572870668/artifacts/455870244

From some feedback on pkg-zone Discord, it seems this issue comes from people using "PS4 explorer" to create and copy the plugins and folders. PS4 explorer creates folders with wrong permissions, and then it's impossible to write or execute files from there.

I think we can close this issue now since it's not related to the Cheat Manager, but an external app messing with folder permissions.
