### ISSUE TITLE
some cheats not working.

### ISSUE THREAD

**Issue by Buts0g** [bucanero/PS4CheatsManager#73]
good eve..
can someone help me to fix some issue on goldhen cheats manager?my daughter playing this game CUSA05170 v.1.00 and upon checking it has 2 cheats on Goldhen Cheats Manager..this morning the cheats still working but when she try this game tonight..its not showing anymore cheats on cheats menu while playing..can you please help me,my daughter really love this game.upon checking on ps4 explorer..its a mc4 file cheat.i really wonder how to fix this and what happen..i hope someone can help me.
Good eve and thank you in advance.
Merry Christmas to all.

**Comment by bucanero** [comment]
the cheat manager has nothing to do with applying the cheats, that's done by the GoldHEN payload. You should check with the cheat creators or ask on discord.

**Comment by bucanero** [comment]
For more info about cheats, check this message: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42
