### ISSUE TITLE
Cheats problem PS4

### ISSUE THREAD

**Issue by GalaxyNET** [bucanero/PS4CheatsManager#76]
Hi, most of the cheats doesn't work for base edition and backport patch. (Pang Adventures, Mega Man 11)
Example: Cheats version are 1.00 and the game on console is 1.01 with the backport patch. (Cheats not found for title id.)

**Comment by bucanero** [comment]
the cheat manager has nothing to do with applying the cheats, that's done by the GoldHEN payload. You should check with the cheat creators or ask on discord.

For more info about cheats, check this message: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42
