### ISSUE TITLE
Ps4 slim freeze

### ISSUE THREAD

**Issue by DragonLord7791** [bucanero/PS4CheatsManager#77]
the problem persists every time you update your program. You need to fix this problem which is the following. Sometimes when I access the cheat manager menu the ps4 freezes. It happened to me many times. Even after this problem the whole ps4 configuration was deleted and I had to reinstall all the games. Please fix the problem Thankyu

**Comment by bucanero** [comment]
The cheat menu on the XMB is handled by the Goldhen plugin, it has nothing to do with the Cheats Manager app.

If you have issues accessing the cheat menu on the XMB while playing a game report it to the Goldhen repository.
