### ISSUE TITLE
[v1.03][fw6.72] Patches list doesn't show up

### ISSUE THREAD

**Issue by IRONB0SS** [bucanero/PS4CheatsManager#83]
![Screenshot 2023-01-25 233045](https://user-images.githubusercontent.com/97769328/214676870-a41f7005-4787-48a4-8a01-f81ca69339a6.jpg)

**Comment by bucanero** [comment]
I know that @illusion0001 has changed the patch format from json to xml. He might know better about this.

**Comment by illusionyy** [comment]
Update db and patches will show up.

**Comment by IRONB0SS** [comment]
@illusion0001 @bucanero thanks
