### ISSUE TITLE
Possible to enter custom cheats?

### ISSUE THREAD

**Issue by bhooshanaj** [bucanero/PS4CheatsManager#84]
I have my own cheat codes, or edited versions of the current one's and would like to use them with the GCM

I know you update repositories using USB but can also put in your own Json file and add to the already existing cheats?

**Comment by bucanero** [comment]
you can add your own .json or .xml files, just check the `/data/GoldHEN/cheats/` folders

Keep in mind, if you use the web update feature, by default all files will be overwritten with downloaded files. (you can change that in the Options menu)
